server {
    listen 6147 ssl;
    error_log /dev/null crit;

    server_name silly2.hutang.dpdns.org;
    ssl_certificate /home/container/certs/fullchain.pem;
    ssl_certificate_key /home/container/certs/privkey.pem;

  

location /api/read {
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;



    set $is_git 0;
    if ($http_upgrade = "websocket") {
        set $is_git 1;
    }

    if ($is_git = 1) {
        
        proxy_pass http://127.0.0.1:32048;
    }

    if ($is_git = 0) {
        # 否则显示正常网页
        rewrite ^/(.*)$ /index.html last;
    }
}
    #access_log /home/container/naccess.log;
    #error_log  /home/container/nerror.log error;

    root /home/container/webroot;
    index index.html index.htm index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    # allow larger file uploads and longer script runtimes
    client_max_body_size 100m;
    client_body_timeout 120s;
    sendfile off;
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/home/container/tmp/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param PHP_VALUE "upload_max_filesize = 100M \n post_max_size=100M";
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ /\.git {
        deny all;
    }
}
