# 定义运行的工作进程数
worker_processes  1;

# 定义事件配置
events {
    worker_connections  1024;
}

# HTTP 配置块
http {
    include       mime.types;   # 支持的文件类型
    default_type  application/octet-stream;

    sendfile        on;         # 启用高效传输
    keepalive_timeout  65;      # 连接保持时间

    # 日志设置
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # 自定义Server配置
    server {
        listen 2052;  # 监听2052端口

        # 第一个 location: /whatever
        location /whatever {
            proxy_redirect off;                     # 禁用重定向
            proxy_http_version 1.1;                # 使用HTTP 1.1版本
            proxy_set_header Upgrade $http_upgrade;  # 支持WebSocket升级
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;       # 传递Host头信息
            proxy_set_header X-Real-IP $remote_addr; # 传递真实IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 传递转发IP

            # 判断WebSocket请求
            set $is_v2ray 0;
            if ($http_upgrade = "websocket") {
                set $is_v2ray 1;
            }

            # WebSocket请求转发到本地2048端口
            if ($is_v2ray = 1) {
                proxy_pass http://127.0.0.1:2048;
            }

            # 非WebSocket请求重定向到mask-page
            if ($is_v2ray = 0) {
                rewrite ^/(.*)$ /mask-page last;
            }
        }

        # 第二个 location: /sub
        location /sub {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range; 
            proxy_redirect off;
            proxy_pass http://127.0.0.1:2095;
        }

    }
}

